#
# This file configures the New Relic Agent.  New Relic monitors Ruby, Java,
# .NET, PHP, Python, Node, and Go applications with deep visibility and low
# overhead.  For more information, visit www.newrelic.com.
#
# Generated May 31, 2021, for version 7.0.0
#
# For full documentation of agent configuration options, please refer to
# https://docs.newrelic.com/docs/agents/ruby-agent/installation-configuration/ruby-agent-configuration
common: &default_settings
  # Required license key associated with your New Relic account.

  # ライセンスキー
  # license_key: 環境変数のNEW_RELIC_LICENSE_KEYから取る
  license_key: <%= NEW_RELIC_LICENSE_KEY %>

  # Your application name. Renaming here affects where data displays in New
  # Relic.  For more details, see https://docs.newrelic.com/docs/apm/new-relic-apm/maintenance/renaming-applications
  app_name: private-isu
  # To disable the agent regardless of other settings, uncomment the following:
  # agent_enabled: false

  # ログは、プロジェクトルート/log/newrelic_agent.log
  log_level: error

  # slow queryの設定
  slow_sql:
    enabled: true
    explain_enabled: true
    record_sql: raw
    explain_threshold: 0.01

  # https://docs.newrelic.com/jp/docs/apm/apm-ui-pages/events/thread-profiler-tool/
  # thread_profiler:
  #   enabled: true

  # デフォルトでtrue
  # agent_enabled: true

  # newrelicに送信する
  # デフォルトでtrue
  # monitor_mode: true

# Environment-specific settings are in this section.
# RAILS_ENV or RACK_ENV (as appropriate) is used to determine the environment.
# If your application has other named environments, configure them here.
development:
  <<: *default_settings
  app_name: private-isu (Development)
staging:
  <<: *default_settings
  app_name: private-isu (Staging)
production:
  <<: *default_settings

  # TODO: 終了直前に諸々無効化する
  # デフォルトでtrue
  # rubyエージェント
  # agent_enabled: false
  # monitor_mode: false

  # デフォルトでtrue
  # transaction_tracer:
  #   explain_enabled: false

  # slow_sql:
  #   enabled: false
  #   explain_enabled: false

  # thread_profiler:
  #   enabled: false
